# Generated by Django 2.0.6 on 2020-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('publisher', models.CharField(blank=True, max_length=20, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('words', models.BigIntegerField(blank=True, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('paper_size', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('introduct', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_num', models.IntegerField(blank=True, null=True)),
                ('sale_num', models.IntegerField(blank=True, null=True)),
                ('pics', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('sup_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'classify',
                'managed': False,
            },
        ),
    ]
